name: Docker Image CI

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: docker-compose build && docker-compose up -d
    - run: npm run test
